# FlexExecutor Configuration for AWS Deployment
# This configuration uses AWS Lambda backend with S3 storage

lithops: 
    # backend: localhost
    # storage: localhost
    backend: aws_lambda
    storage: aws_s3
    data_cleaner: True
    execution_timeout: 300
    log_level: DEBUG # manri --> primer paso 
    # log_format: "%(asctime)s [%(levelname)s] %(name)s -- %(message)s"
    
 
    cost_simulation: True
    performance_tracking: True
    
    # Disable Python version checking
    runtime_version_tolerance: 1
    ignore_runtime_python_version: True

localhost:
    runtime_python_version: "3.10"

aws:
    AWS_ACCESS_KEY_ID: "ASIA4MTWMECOK7U3DCY2"
    AWS_SECRET_ACCESS_KEY: "iHiYbEURizkU1uPhXJJlO9Iiqupc6bsmzeuJik50"
    AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEAkaCXVzLWVhc3QtMSJHMEUCIBbx6/c3U2Sir7DHIKLVx80ygIr22VyArt01T+DS25fEAiEA4lhDwQ0pK/lNXnwcx+LVyM9l6Hn5jziVs2FUlVITZlMq9gIIURAAGgw4NTE3MjU1MjUxNDgiDN2fPyUrrBdKBdXhQSrTApywZ5en4HybrdrPAKrTSsrD+iy4LgScl1cH7Ci0tiOxbDwQXYVONpH6vYbTg/uIbjvjn7PEEovCor0QrVbSLTC9kDLqxJTqJjgVk0TxIBQ7p9kex/5kMP5BiI5sXBnUWWaG3gW0UhJ/8mqAgLe0+7z947Q+rSfdo6Pnn81BSBAj0AJaCx0KpD469tARvtIy7z6TftrJkLM/CLrhqiYbLRvHOEaxhiUqGbkcLCB5M8m/5qOeK+hTv8e869fTV1jrXCWQOMBzfaxqFwVWinX+gWZ2yhlXM2IRigLDomKyzUt7NddvbL9GuvJUgELWKekFGEqm/E48V1Itb3ECAD+Wm+B6Y39CSfPr2FwYWtVlH0IiiP4swCRuLoT435aP3eqE/QGt5nsEhdTdrrBSlLaE9DilGVF/pBpuvLobZJHGPNmq3O3wj3pRYoC2EmOH1y9BnByRfzDk+fnEBjqnASHK2/6gh812+H7TsXHlfQAECkrrzbtbWaHZETeWEKKfHgphpxvCigbSJg3YRctD4+fOSa6azpW3BJ8X/nAhDWIX241Fr2qCCy//iV3+n/BiuVGJGRKZlUsRtdASQBiWcy3Uj3BLtMNsCli8hJ90mIKoikcnh6rZ7s+aPuoNqjOQ8FotR0NpX5ADU1BYXZ8t/sq8gHnNinZSi4AHnGSZYZISdu1jz3mr"
    region: us-east-1

 

# AWS Lambda configuration : ARM64 vs x86_64 architecture
aws_lambda:
    execution_role: arn:aws:iam::851725525148:role/lambdaLithopsExecutionRole
    runtime_timeout: 300
    # runtime_memory: 1024
    # runtime_memory: 512
    runtime_memory: 2048

    ##### ML #####
    # ML ARM64 specific runtime: 
    # runtime: ml_aws_arm64
    # runtime: ml_aws_lambda_arm_greencomp_v1
    
    #####  Titanic x86_64 specific runtime: #####
    # runtime: titanic_aws_lambda_x86_greencomp_v1
    runtime: video_aws_lambda_x86_greencomp_v1
    # runtime: ml_aws_lambda_x86_greencomp_v1
    architecture: x86_64
    
    # Titanic ARM64 specific runtime: 
    # runtime: titanic_aws_lambda_arm_greencomp_v1
    # runtime: titanic_aws_lambda_arm_greencomp_v1_512mb_v2
    # runtime: titanic_aws_lambda_arm_greencomp_v1_2048mb
    # runtime: titanic_aws_lambda_arm_greencomp_v3
    runtime: video_aws_lambda_arm_greencomp_v1
    
    
    
    
    # architecture: arm64

    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # FlexExecutor configuration for AWS Lambda with enhanced energy monitoring
    # Default runtime: 
    # runtime: default-runtime-v312 
    # architecture: x86_64
    max_workers: 1000
    worker_processes: 1
    invoke_pool_threads: 64
    ephemeral_storage: 10240  # Maximum allowed (10GB) for video processing
    check_version: false
    
    environment:
        ENERGY_MONITORING_ENABLED: "true"
        COST_SIMULATION_ENABLED: "true"
        WORKLOAD_TYPE: "flexecutor_ml"
        MEASUREMENT_FUNCTIONS: "prime_function,sleep_function"

aws_s3:
    storage_bucket: lithops-us-east-1-45dk
    region: us-east-1
    
    # Energy metrics storage configuration
    energy_metrics:
        bucket: lithops-us-east-1-45dk
        prefix: "energy-metrics/flexecutor/"
        retention_days: 30
