# FlexExecutor Configuration for AWS Deployment
# This configuration uses AWS Lambda backend with S3 storage

lithops: 
    backend: aws_lambda
    storage: aws_s3
    data_cleaner: True
    execution_timeout: 300
    log_level: DEBUG # manri --> primer paso 
    # log_format: "%(asctime)s [%(levelname)s] %(name)s -- %(message)s"
    
 
    cost_simulation: True
    performance_tracking: True
    
    # Disable Python version checking
    runtime_version_tolerance: 1
    ignore_runtime_python_version: True

aws:
    aws_access_key_id: ASIA4MTWMECOIRWXVITX
    aws_secret_access_key: q0zL74aeCLZlo/YL6DVoIl5MeOxt//92VisRD8xD
    aws_session_token: IQoJb3JpZ2luX2VjEAoaCXVzLWVhc3QtMSJGMEQCIFUBEduL5dwEUhsJyUAsPrz0BBZNlTdeyIOSGa2TGSxoAiBKsqBl5MIgCoBeGhyLD3j9fQFnmpyfire8iJotFbsn5Cr2AghCEAAaDDg1MTcyNTUyNTE0OCIMTf4XURMxWebk9D4OKtMC508E3U191vrJ7boBRxUmuRABRvYKsXIdbmDdsNvr+QOS0BQ4dVV4jf2T6kc4SMzm2eGMJW4GC1QYtG/vTc6tEQE+R7LU7iKgPT2rJkSxi9WArGuXovFR9pBDXrj33N64vXyAK16vLWCj6l9FLvqn6peB5+huNVTRzl4t6591NeZYStPssaDW8xqy+caFo99lhgZGufJhKPuVf7PuHAv+B+8/XMi79BKbg9InoBFEz4y/eQeoMfJjRe6yQESuj02yC7mIPUaNlappE3DsuOgmjggewNmswLjzx6R7uUkitL3VKYw5R8ejuFcruwDEKFGg3LXDqMnwwinPFNByysboP7hyKxCIwXqocgJI97UZQPdydiYEycOpDE/qx/hbQJRuJdm6J4Whj2OCtTMWRckoxqDApVRkcT4wXmnocOdHdzJMUHLSVXj+TxP0tR0FI83wkiGmMMf0wcQGOqgBUCGRpkvuz7B47Ij21QMcSyhdBgKL5GmI+ElFD7OC7GP3z7hw/dazy0EPFfYCkPo+Emfr1bmpo6Qaf7TTihLlxKDJ8nIwZ2AFP0CdTF3VslSftRi8dI8KnuyGyDiwiHkLW7BTuF90mHMPBnkxrkSyJokQi3BC+OP1+Mv4fysCG43SA+WUO8dFxSmnoY7bwSKCYt6/vKn2PSGDmeHV22tFFYwEm+Y/UBW3
    region: us-east-1

 

# AWS Lambda configuration : ARM64 vs x86_64 architecture
aws_lambda:
    execution_role: arn:aws:iam::851725525148:role/lambdaLithopsExecutionRole
    runtime_timeout: 300
    runtime_memory: 2048

    # ML ARM64 specific runtime: 
    runtime: ml_aws_arm64
    architecture: arm64
    
    # Titanic x86_64 specific runtime: 
    # runtime: titanic_aws_lambda
    # architecture: x86_64
    
    # Titanic ARM64 specific runtime: 
    # runtime: titanic_aws_lambda_arm_greencomp
    # architecture: arm64

    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # FlexExecutor configuration for AWS Lambda with enhanced energy monitoring
    # Default runtime: 
    # runtime: default-runtime-v312 
    # architecture: x86_64
    max_workers: 1000
    worker_processes: 1
    invoke_pool_threads: 64
    ephemeral_storage: 1024
    check_version: false
    
    environment:
        ENERGY_MONITORING_ENABLED: "true"
        COST_SIMULATION_ENABLED: "true"
        WORKLOAD_TYPE: "flexecutor_ml"
        MEASUREMENT_FUNCTIONS: "prime_function,sleep_function"

aws_s3:
    storage_bucket: lithops-us-east-1-45dk
    region: us-east-1
    
    # Energy metrics storage configuration
    energy_metrics:
        bucket: lithops-us-east-1-45dk
        prefix: "energy-metrics/flexecutor/"
        retention_days: 30
