# FlexExecutor Configuration for AWS Deployment
# This configuration uses AWS Lambda backend with S3 storage

lithops: 
    # backend: localhost
    # storage: localhost
    backend: aws_lambda
    storage: aws_s3
    data_cleaner: True
    execution_timeout: 300
    log_level: DEBUG # manri --> primer paso 
    # log_format: "%(asctime)s [%(levelname)s] %(name)s -- %(message)s"
    
 
    cost_simulation: True
    performance_tracking: True
    
    # Disable Python version checking
    runtime_version_tolerance: 1
    ignore_runtime_python_version: True

localhost:
    runtime_python_version: "3.10"

aws:
    AWS_ACCESS_KEY_ID: "ASIA4MTWMECODOTMORFN"
    AWS_SECRET_ACCESS_KEY: "4vNeqm2FareW0webc2Ayo+Xd3WusxB0cwzwatEQF"
    AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEEcaCXVzLWVhc3QtMSJGMEQCIBKZ0OyMZH/rf+Nv5lqoE4FiBJOQozCgIWxPZgegSpq6AiAfdURiziOHHimUGDCo+kFLGnR7W9KEp82T3XGxki/rhyr2Agh/EAAaDDg1MTcyNTUyNTE0OCIMoI0PUdCBwLRhcif6KtMCGqKK0JrmlijliqKd+rg9Dy1pJ2jUtiXp4ZiSRtW1qbQawLIVhfpKzWtSd/dTpLAbpJRUtPH21IuF7jJF3M+J+EVMMBFEE2/5KhaxSGh6c/+9RiKQy7b/NslghVehJIUBNKNdrK6Lc2dqdX21rPlGKLXurSysEFNAVJ9KySRVLMFXB7dB2OSZrKqaNngx05eGL4QmH/k7a+NRmipTWLlFoZrC2NHLbK7/xveBVVKag/4keeYqX39Acu9d8BMeaFynPEgAIgiojnljyeNQGFRnW8kSfIIRQGUfGkjHrhryznFkdO8gkIayN+R5gONKOdvxhzqKbGR2hKy9uxe+wdK4k6unvbDsh/90RL65+xISRMtg1i4xZiOU/xrROV+T9aSof8V8y84JFb25rNBTUqwrPJV3fEgfpClTDEj7LnsrDdmJoZX7dpDlOYEkRTD+TzGcoGalMPuiz8QGOqgB4V2OtrKW706N9hfH+vZTRHLH7mXIqyLXur0AeModkdvoVh0tchlHSs2u61ncZigyVfMDeOdLYKjOyIzab/IWoSg4u9nRzCSCwu/+xdxpnfPP+dwW/oWkkR7qpXE4y+9EjkaWzPEP4CgFLuKtS4IrgGp0TpX+74MVWnkNoS0p715KAT4bphAPXbUpT9yrNjgXKMI6oqTwcnUabG2289nsG1IdTUZc4/Sy"
    region: us-east-1

 

# AWS Lambda configuration : ARM64 vs x86_64 architecture
aws_lambda:
    execution_role: arn:aws:iam::851725525148:role/lambdaLithopsExecutionRole
    runtime_timeout: 300
    runtime_memory: 2048

    # ML ARM64 specific runtime: 
    # runtime: ml_aws_arm64
    # architecture: arm64
    
    # Titanic x86_64 specific runtime: 
    runtime: titanic_aws_lambda
    architecture: x86_64
    
    # Titanic ARM64 specific runtime: 
    # runtime: titanic_aws_lambda_arm_greencomp
    # architecture: arm64

    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # FlexExecutor configuration for AWS Lambda with enhanced energy monitoring
    # Default runtime: 
    # runtime: default-runtime-v312 
    # architecture: x86_64
    max_workers: 1000
    worker_processes: 1
    invoke_pool_threads: 64
    ephemeral_storage: 1024
    check_version: false
    
    environment:
        ENERGY_MONITORING_ENABLED: "true"
        COST_SIMULATION_ENABLED: "true"
        WORKLOAD_TYPE: "flexecutor_ml"
        MEASUREMENT_FUNCTIONS: "prime_function,sleep_function"

aws_s3:
    storage_bucket: lithops-us-east-1-45dk
    region: us-east-1
    
    # Energy metrics storage configuration
    energy_metrics:
        bucket: lithops-us-east-1-45dk
        prefix: "energy-metrics/flexecutor/"
        retention_days: 30
