# FlexExecutor Configuration for AWS Deployment
# This configuration uses AWS Lambda backend with S3 storage

lithops: 
    # backend: localhost
    # storage: localhost
    backend: aws_lambda
    storage: aws_s3
    data_cleaner: True
    execution_timeout: 300
    log_level: DEBUG # manri --> primer paso 
    # log_format: "%(asctime)s [%(levelname)s] %(name)s -- %(message)s"
    
 
    cost_simulation: True
    performance_tracking: True
    
    # Disable Python version checking
    runtime_version_tolerance: 1
    ignore_runtime_python_version: True

localhost:
    runtime_python_version: "3.10"

aws:
    AWS_ACCESS_KEY_ID: "ASIA4MTWMECOLBDEHJ6K"
    AWS_SECRET_ACCESS_KEY: "iHUaY1TMpQKUUExGk6udzIV/EG+rk4f5DarBE2Pn"
    AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEHsaCXVzLWVhc3QtMSJIMEYCIQCFsbdPGCOWEo16DHAr08U3GglF4za9JpwQmWjq23EIMQIhAPmGAeUdCr9g9IijO9oB6K7j0RiSsjteAh1SG9RfI7QrKv8CCMT//////////wEQABoMODUxNzI1NTI1MTQ4IgyHHlyWzmuLCQmScEgq0wKkr4OvwU1Y6ggDDysWQxLpKgiawGxHVBxMSE/ZIB28Guu/Ccposdu7t2L6i8B/abcYdi5OjDnu6iaAEDx1w52wynMSWLRPD4pwzhYoRzhoyWKrfk2d0YsAe/vOFVzqDVwgwMFInAXW2CvcxGfw/1rhQ5cGgsJj1hswR0hdasoeUOSc5dBIahVw1JzDX0UrssjrlDM6Q+SA9yzULhfjsK+39TbccCO43BvDaMXEBm8c98XcpAXHxzigvMtreKIQ+GxtmSWnsmiT5uLDFhW/h5B+KsveJBQd9r+I/20uXsvIh7OED40GigMk4k9BUoQUDlFaLDgWtoeGBBoQnssMrMlzbKzqHof/8g1Z0FgabNGRRdJPQwmxWC+swXhDlZF9iDqCBij0LtbTiX4OhGCopaubl5hNANdK5DIw9PaRJK9v/e7Acvk2KOy5hmFFgCuQi9K4azMw+JGTxQY6pgGEDrMdW1IFJVxaq4zkjgygcvDs52NX7Cdsi0ARJWpfT8IWVXT0CXjj9RNplBUfKdmWh3Dz/WdWNSunkHc2v/O/mEBuXnav1Di559ugR1Q8jYQYdwMRMzEDIce10JFNnbivEz4W8OwepzZZvqTMq7wf0Bsqid1LHMe6Kb7jsHp3e661OxOljiIm5mh0nQ42H/hP1IuHpD/8kQwicIvO/uR6MiQ0RQHg"
    region: us-east-1


# AWS Lambda configuration : ARM64 vs x86_64 architecture
aws_lambda:
    execution_role: arn:aws:iam::851725525148:role/lambdaLithopsExecutionRole
    runtime_timeout: 300
    # runtime_memory: 1024
    # runtime_memory: 512
    runtime_memory: 2048

    # architecture: arm64
    architecture: x86_64

    ##### ARM64 specific runtime: 
    # runtime: titanic_aws_lambda_arm_greencomp_v1
    # runtime: ml_aws_lambda_arm_greencomp_v1
    # runtime: video_aws_lambda_arm_greencomp_v1

    #####  x86_64 #####
    # runtime: default-runtime-v312 
    # runtime: titanic_aws_lambda_x86_greencomp_v1
    runtime: video_aws_lambda_x86_greencomp_v2
    # runtime: ml_aws_lambda_x86_greencomp_v1



    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # FlexExecutor configuration for AWS Lambda with enhanced energy monitoring
    # Default runtime: 
    # runtime: default-runtime-v312 
 
    max_workers: 1000
    worker_processes: 1
    invoke_pool_threads: 64
    ephemeral_storage: 10240  # Maximum allowed (10GB) for video processing
    check_version: false
    
    environment:
        ENERGY_MONITORING_ENABLED: "true"
        COST_SIMULATION_ENABLED: "true"
        WORKLOAD_TYPE: "flexecutor_ml"
        MEASUREMENT_FUNCTIONS: "prime_function,sleep_function"

aws_s3:
    storage_bucket: lithops-us-east-1-45dk
    region: us-east-1
    
    # Energy metrics storage configuration
    energy_metrics:
        bucket: lithops-us-east-1-45dk
        prefix: "energy-metrics/flexecutor/"
        retention_days: 30
