# FlexExecutor Configuration for AWS Deployment
# This configuration uses AWS Lambda backend with S3 storage

lithops: 
    # backend: localhost
    # storage: localhost
    backend: aws_lambda
    storage: aws_s3
    data_cleaner: True
    execution_timeout: 300
    log_level: DEBUG # manri --> primer paso 
    # log_format: "%(asctime)s [%(levelname)s] %(name)s -- %(message)s"
    
 
    cost_simulation: True
    performance_tracking: True
    
    # Disable Python version checking
    runtime_version_tolerance: 1
    ignore_runtime_python_version: True

localhost:
    runtime_python_version: "3.10"

aws:
    AWS_ACCESS_KEY_ID: "ASIA4MTWMECOCNLDKURC"
    AWS_SECRET_ACCESS_KEY: "fjTiH0/7JcC6cHPyRgAc0oQCCafH2bo9nCEwtXeN"
    AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEDkaCXVzLWVhc3QtMSJIMEYCIQDCYiXn3eT8LmiqC8VNCoRoZlTRcs3ZmvbbLwLPApRkrwIhAJmOHK9gpazix4ctZQLMDMxQ/LMsVW9JSx159P35CyQ9Kv8CCIL//////////wEQABoMODUxNzI1NTI1MTQ4IgyKyUYipjEbXnP07AIq0wJEj2ZilaN1ZWRqynvz/S4AnI5T1opJYOw/Vp5/yIWOjDBCd1AIp/g/sBDVKs6F8PtsYs1AqW/IeDAuWi5rBV+OVY9phyGLH+fLJdGbFkn45IdqQte4jA5hyK3bc08cWL1co+DFrRq0KnHjxTat/mjNnu2HvVCAXs31O62wSgpOJDITCS242zPa9P5aPOwPkJVyW5A1TYp1BJuU4yYDHUMxs6RjWaMd9lkg3FaUDtP/gfI2Vz3WEnO1a3aNpgoU+WgpdxLQg/qNvn1cwd/6ohXciO3TkRMpIKM4tWIh0r9vJD3nBC7cP1S0H1zf91kwYLRUbjBYo/h4FQlx9gls/KkWmJ0n8uuwBOjkqFXGfti1jYYQww7qan9VNYBRRBMYm1IPw3tQknt34goUSxtyySVOWONW0kpE6C2wUibF/6uz63AeoYedZElQiiuT/Jwb7W8RoPsw9sKExQY6pgFTFNDI7x1TxhA0t/HbQpM+6r0UWWOJqrm//IQg43KJhgLeVYou0a48HzGtlDNkl2PDeXhHUyrKEalpsDki//NnOoeGmPmC/IMaF/QhVduJW33DdzFxdQdspj890Ov0saXbv5qOzb47/Z0i7NXk2pakZpdWhfHxBwCokfEF/buexS/RSnDnwe9N6i+P3mJCWRGA7PWUhQuyeylozy7I/vIn8axZ4PcS"
    region: us-east-1

 

# AWS Lambda configuration : ARM64 vs x86_64 architecture
aws_lambda:
    execution_role: arn:aws:iam::851725525148:role/lambdaLithopsExecutionRole
    runtime_timeout: 300
    # runtime_memory: 1024
    # runtime_memory: 512
    runtime_memory: 2048

    ##### ML #####
    # ML ARM64 specific runtime: 
    # runtime: ml_aws_arm64
    # runtime: ml_aws_lambda_arm_greencomp_v1
    
    #####  Titanic x86_64 specific runtime: #####
    # runtime: titanic_aws_lambda_x86_greencomp_v1
    runtime: video_aws_lambda_x86_greencomp_v1
    # runtime: ml_aws_lambda_x86_greencomp_v1
    architecture: x86_64
    
    # Titanic ARM64 specific runtime: 
    # runtime: titanic_aws_lambda_arm_greencomp_v1
    # runtime: titanic_aws_lambda_arm_greencomp_v1_512mb_v2
    # runtime: titanic_aws_lambda_arm_greencomp_v1_2048mb
    # runtime: titanic_aws_lambda_arm_greencomp_v3
    # runtime: video_aws_lambda_arm_greencomp_v1
    
    
    
    
    # architecture: arm64

    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # FlexExecutor configuration for AWS Lambda with enhanced energy monitoring
    # Default runtime: 
    # runtime: default-runtime-v312 
    # architecture: x86_64
    max_workers: 1000
    worker_processes: 1
    invoke_pool_threads: 64
    ephemeral_storage: 10240  # Maximum allowed (10GB) for video processing
    check_version: false
    
    environment:
        ENERGY_MONITORING_ENABLED: "true"
        COST_SIMULATION_ENABLED: "true"
        WORKLOAD_TYPE: "flexecutor_ml"
        MEASUREMENT_FUNCTIONS: "prime_function,sleep_function"

aws_s3:
    storage_bucket: lithops-us-east-1-45dk
    region: us-east-1
    
    # Energy metrics storage configuration
    energy_metrics:
        bucket: lithops-us-east-1-45dk
        prefix: "energy-metrics/flexecutor/"
        retention_days: 30
