lithops:
    # backend: localhost         
    backend: k8s     
    storage: minio

 

k8s:
    kubecfg_path: /home/users/iarriazu/.kube/config
    # runtime: iarriazu/lithops-runtime2:latest    
    runtime: iarriazu/flexecutor-lithops
    # runtime: iarriazu/inigo_runtime
    
    # docker_image: iarriazu/lithops-runtime2:latest
    
    runtime_memory: 2048           # Memory per worker pod
    runtime_timeout: 600          # Individual worker timeout (20 minutes)
    # master_timeout: 1800           # Master job timeout (30 minutes) 
    # runtime_cpu: 2                 # CPU per worker (2 vCPUs)
    # max_workers: 50                # Maximum concurrent workers
    namespace: inigo-jobs-energy
    node_selector:
        lithops-target-node: "true" # tu nodeSelector

minio:
    storage_bucket: test-bucket
    endpoint: http://192.168.5.24:9000
    access_key_id: lab144
    secret_access_key: astl1a4b4

# ''''    
#  k8s:
## worker_processes: 4 # posible error : logico ver que pasa cuando 1 --> poner por defecto comentado
# principal localizacion: /home/users/iarriazu/.lithops/config
